title: "Mihir Thakkar"
description: >
  Seasoned Data Science and FinTech Expert.
  <br><br>
  Transforming Business Growth through Data-driven Strategies
logo: "/Images/Circle.jpg"
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
