# --- THEME SETTINGS -------------------------------------------------
# Choose a built-in color skin: default, air, aqua, contrast, dark, dirt, neon,
# mint, plum, sunrise
minimal_mistakes_skin    : "dark"

# --- SITE SETTINGS --------------------------------------------------
locale                   : "en-US"
title                    : "Mihir Thakkar"
title_separator          : "-"
subtitle                 : "root@OstrichAI | Patent-backed AI Infra"
name                     : "Mihir Thakkar"
description              : "Founder @ Ostrich AI 路 GAFAI Delegate 路 Building consent-aware, auditable AI systems."
url                      : "https://mihir-ai-lab.github.io"   # full URL
baseurl                  : ""                                 # leave blank
repository               : "mihir-ai-lab/mihir-ai-lab.github.io"
teaser                   :
logo                     : "/assets/images/mihir.png"         # upload this image
masthead_title           :                                    # blank shows full title
breadcrumbs              :
words_per_minute         : 200
enable_copy_code_button  :

# --- COMMENTS (unchanged defaults) ---------------------------------
comments:
  provider               :

# --- SEO (unchanged defaults) --------------------------------------
google_site_verification :
bing_site_verification   :

# --- SOCIAL SHARING -------------------------------------------------
twitter:
  username               : "0xmthakkar"

social:
  type                   : "Person"
  name                   : "Mihir Thakkar"
  links:
    - "https://linkedin.com/in/thakkarmihir"
    - "https://github.com/mihir-ai-lab"
    - "https://twitter.com/0xmthakkar"

# --- ANALYTICS (optional) ------------------------------------------
analytics:
  provider               :
  google:
    tracking_id          :
    anonymize_ip         :

# --- SITE AUTHOR ----------------------------------------------------
author:
  name       : "Mihir Thakkar"
  avatar     : "/assets/images/mihir.png"   # ensure this file exists
  bio        : "Global AI Delegate 路 Patent No. 567234 路 Scaling AI infra without the chaos."
  location   : "Mumbai, India"
  email      : "mthakkar@ostrich-ai.com"
  links:
    - label: "LinkedIn"
      icon : "fab fa-fw fa-linkedin"
      url  : "https://linkedin.com/in/thakkarmihir"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/mihir-ai-lab"
    - label: "Twitter"
      icon : "fab fa-fw fa-twitter"
      url  : "https://twitter.com/0xmthakkar"

# --- FOOTER SOCIAL LINKS -------------------------------------------
footer:
  links:
    - label: "LinkedIn"
      icon : "fab fa-fw fa-linkedin"
      url  : "https://linkedin.com/in/thakkarmihir"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/mihir-ai-lab"
    - label: "Twitter"
      icon : "fab fa-fw fa-twitter"
      url  : "https://twitter.com/0xmthakkar"

# --- READING / BUILD DEFAULTS (unchanged) --------------------------
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# --- CONVERSION (defaults) -----------------------------------------
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# --- KRAMDOWN (defaults) -------------------------------------------
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --- SASS / SCSS (defaults) ----------------------------------------
sass:
  sass_dir: _sass
  style: compressed

# --- OUTPUT (defaults) ---------------------------------------------
permalink: /:categories/:title/
timezone: 

# --- PAGINATION (defaults) -----------------------------------------
paginate: 5
paginate_path: /page:num/

# --- PLUGINS (keep defaults) ---------------------------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# --- ARCHIVES, HTML COMPRESSION, DEFAULTS (unchanged) --------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments:
      share: true
      related: true
