# --- THEME SETTINGS ---
minimal_mistakes_skin    : "dark"

# --- SITE SETTINGS ---
locale                   : "en-US"
title                    : "Mihir Thakkar"
title_separator          : "-"
subtitle                 : "Building a Secure & Compliant AI Ecosystem"
name                     : "Mihir Thakkar"
description              : "Global AI Delegate - India by the Global Alliance for Artificial Intelligence"
url                      : "https://mihir-ai-lab.github.io"
baseurl                  : ""
repository               : "mihir-ai-lab/mihir-ai-lab.github.io"
logo                     : "/assets/images/mihir.png"
masthead_title           :
words_per_minute         : 200

# --- COMMENTS ---
comments:
  provider               :

# --- SEO ---
google_site_verification :
bing_site_verification   :

# --- SOCIAL SHARING ---
twitter:
  username               : "0xmthakkar"

social:
  type                   : "Person"
  name                   : "Mihir Thakkar"
  links:
    - "https://linkedin.com/in/thakkarmihir"
    - "https://github.com/mihir-ai-lab"
    - "https://twitter.com/0xmthakkar"

# --- ANALYTICS (optional) ---
analytics:
  provider               :
  google:
    tracking_id          :
    anonymize_ip         :

# --- SITE AUTHOR ---
author:
  name       : "Mihir Thakkar"
  avatar     : "/assets/images/mihir.png"
  bio        : "Global AI Delegate - India · Scaling AI infra without the chaos."
  location   : "Mumbai, India"
  email      : "mthakkar@ostrich-ai.com"
  links:
    - label: "LinkedIn"
      icon : "fab fa-fw fa-linkedin"
      url  : "https://linkedin.com/in/thakkarmihir"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/mihir-ai-lab"
    - label: "Twitter"
      icon : "fab fa-fw fa-twitter"
      url  :
