title: "Mihir Thakkar"
logo: "/images/Circle.png?raw=true"
description: >
  Seasoned Data Science and FinTech Expert.
  <br><br>
  Supercharge Your Data Journey! Join me on 
  [The Data Science Guy Live Hub](https://thedatascienceguy.live/hub/login) 
  for Collaborative Coding Adventures.
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
