title: "The Data Science Guy"
logo: "/images/Logo%20Full.png?raw=true"
description: >
  Certified Data Science and FinTech Expert.
  
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
