# --- THEME ----------------------------------------------------------
remote_theme        : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"            # we’ll override colours below

# --- SITE -----------------------------------------------------------
title       : "Mihir Thakkar"
subtitle    : "Data • Infra • People"
description : "Global AI Delegate – India | Founder, Ostrich AI"
url         : "https://mihir-ai-lab.github.io"
baseurl     : ""
repository  : "mihir-ai-lab/mihir-ai-lab.github.io"
logo        : "/assets/images/mihir.png"

# --- SOCIAL ---------------------------------------------------------
twitter:
  username : "0xmthakkar"

social:
  type  : "Person"
  name  : "Mihir Thakkar"
  links :
    - "https://linkedin.com/in/thakkarmihir"
    - "https://github.com/mihir-ai-lab"
    - "https://twitter.com/0xmthakkar"

author:
  name   : "Mihir Thakkar"
  avatar : "/assets/images/mihir.png"
  bio    : "AI infra architect · Patent #567234 · GAFAI Delegate"
  email  : "mthakkar@ostrich-ai.com"

footer:
  links:
    - label: "LinkedIn"  icon: "fab fa-fw fa-linkedin"  url: "https://linkedin.com/in/thakkarmihir"
    - label: "GitHub"    icon: "fab fa-fw fa-github"    url: "https://github.com/mihir-ai-lab"
    - label: "Twitter"   icon: "fab fa-fw fa-twitter"   url: "https://twitter.com/0xmthakkar"

# --- BUILD / ASSETS -------------------------------------------------
exclude : [test, docs, node_modules, vendor, Gemfile*]

sass:
  sass_dir  : _sass
  style     : compressed
  load_paths:
    - assets/css

plugins: [jekyll-include-cache]   # (we keep the default ones GitHub adds)

# --- CUSTOM COLOURS -------------------------------------------------
# Override theme colours to match OstrichAI Webflow site
# Create file: assets/css/custom.scss (see below)
