title: Mihir Thakkar # your name (or website title) here
logo: "/images/DP3.jpg?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://wa.me/917021684214">Connect on Whatsapp</a>
  <br><br>
  <a href="www.linkedin.com/in/thedatascienceguy">View My LinkedIn Profile</a>   
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HW3XTE97VR"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HW3XTE97VR');
</script>
