title: "Mihir Thakkar"
logo: "/images/logo.png?raw=true"
description: >
  Seasoned Data Science and FinTech Expert.
  <br><br>
  Transforming Business Growth through Data-driven Strategies
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
