title: Mihir Thakkar # your name (or website title) here
logo: "/images/Circle.png?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://wa.me/917021684214">Connect on Whatsapp</a>
  <br><br>
  <a href="www.linkedin.com/in/thedatascienceguy">View My LinkedIn Profile</a>   
  
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-HW3XTE97VR # Google tag here
