title: The Data Science Guy # your name (or website title) here
logo: "/images/Icon.png?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  We help start- ups & SME’s tackle complex problems, automate tasks, and address recurring issues.
  <br><br>
  Our team of experts has the skillset to assist you with:
  - Branding Strategies
  - Business Analysis
  - Data Science
  <br><br>
  <a href="https://www.linkedin.com/in/thedatascienceguy">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
