title: "Mihir Thakkar"
description: >
  Seasoned Data Science and FinTech Expert.
  <br><br>
  Transforming Business Growth through Data-driven Strategies
logo: "https://raw.githubusercontent.com/Mihir-Ai-lab/The_Data_Science_Guy/main/Images/Logo%20Full.png"
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
