title: "Mihir Thakkar"
description: >
  Seasoned Data Science and FinTech Expert.
  <br><br>
  Transforming Business Growth through Data-driven Strategies
logo: "/images/Circle.png?raw=true"
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

header_pages:
  - index.md
  - about.md
  - tech-stack.md
  - portfolio.md
  - github-stats.md
  - credits.md
