title: Mihir Thakkar 
logo: "/images/Circle.png?raw=true" 
description: > 
  #Seasoned Data Science and FinTech Expert. | Transforming Business Growth through Data-driven Strategies
  <br><br>
    
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here
