# --- Theme ----------------------------------------------------------
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# --- Site -----------------------------------------------------------
title       : "Mihir Thakkar"
subtitle    : "Building a Secure & Compliant AI Ecosystem"
description : "Global AI Delegate — India | Patent-backed AI Infra"
url         : "https://mihir-ai-lab.github.io"
baseurl     : ""
repository  : "mihir-ai-lab/mihir-ai-lab.github.io"
logo        : "/assets/images/mihir.png"

# --- Social ---------------------------------------------------------
twitter:
  username: "0xmthakkar"

social:
  type : "Person"
  name : "Mihir Thakkar"
  links:
    - "https://linkedin.com/in/thakkarmihir"
    - "https://github.com/mihir-ai-lab"
    - "https://twitter.com/0xmthakkar"

author:
  name   : "Mihir Thakkar"
  avatar : "/assets/images/mihir.png"
  bio    : "Patent #567234 · GAFAI Delegate · Turning AI chaos into infrastructure."
  email  : "mthakkar@ostrich-ai.com"
  links:
    - label: "LinkedIn"
