title: "Mihir Thakkar"
description: >
  Seasoned Data Science and FinTech Expert. | Transforming Business Growth through Data-driven Strategies
  <br><br>
  <p align="center"><img src="https://raw.githubusercontent.com/Mihir-Ai-lab/The_Data_Science_Guy/main/Images/Text%20Banner.png"></p>
logo: "/images/Circle.png?raw=true"
theme: jekyll-theme-minimal
google_analytics: G-HW3XTE97VR # Google tag here

